---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppName:
    Type: String
    Default: dwc
  Env:
    Type: String
    Default: poc
  BasicExecRole: 
    Type: String
    Default: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
Resources:
  IAMRoleCallsigndataUpdaterRoleForDirewolf:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
      - !Ref BasicExecRole
      MaxSessionDuration: 3600
      RoleName: !Sub "${AppName}-${Env}-callsign-data-updater-role"
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AppName}-${Env}-callsign-data"
            Action:
            - "dynamodb:PutItem"
            - "dynamodb:DescribeTable"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:ListTagsOfResource"
            - "dynamodb:Query"
            - "dynamodb:UpdateItem"
            - "dynamodb:GetRecords"
            Effect: "Allow"
            Sid: "VisualEditor0"
        PolicyName: !Sub "${AppName}-${Env}-callsign-data-table-policy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
  IoTPolicyForDireWolf:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IoT::Policy"
    DeletionPolicy: "Retain"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource: "*"
          Action: "*"
          Effect: "Allow"
      Tags: []
      PolicyName: !Sub "${AppName}-${Env}-data-collection-iot-policy"

Outputs:
  IAMRoleCallsigndataUpdaterRoleForDirewolfArn:
    Value: !GetAtt IAMRoleCallsigndataUpdaterRoleForDirewolf.Arn
    Description: IAM role used by both lambdas in the project
    Export:
      Name: !Sub "${AppName}-${Env}-IAMRoleCallsigndataUpdaterRoleForDirewolf"
  IoTPolicyForDireWolfArn:
    Value: !GetAtt IoTPolicyForDireWolf.Arn
    Description: IoT policy used in the project
    Export:
      Name: !Sub "${AppName}-${Env}-IoTPolicyForDireWolf"