---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppName:
    Type: String
    Default: dwc
  Env:
    Type: String
    Default: poc
Resources:
  LambdaFunctionCallsigndataupdater:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "index.lambda_handler"
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          def lambda_handler(event, context):
              cs_table = os.environ['CALLSIGNTABLE']
              print(event)
              callsign = event["properties"]["name"]
              dynamodb = boto3.client('dynamodb')
              dynamodb.put_item(TableName=cs_table,
                  Item={
                      'callsign': {'S': callsign},
                      'geojson': {'S': str(event)}
                  })
              return {
                  'statusCode': 200,
                  'body': event
              }
      Role: 
        Fn::ImportValue: !Sub "${AppName}-${Env}-IAMRoleCallsigndataUpdaterRoleForDirewolf"
      FileSystemConfigs: []
      FunctionName: !Sub "${AppName}-${Env}-callsign-data-updater"
      Runtime: "python3.10"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/callsign-data-updater"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CALLSIGNTABLE: !Sub "${AppName}-${Env}-callsign-data"
      Architectures:
      - "x86_64"
  DynamoDBTableCallsigndata:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: !Sub "${AppName}-${Env}-callsign-data"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "callsign"
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "callsign"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"
      Tags: []
      TimeToLiveSpecification:
        Enabled: false
Outputs:
  DynamoDBTableCallsigndataArn:
    Value: !GetAtt DynamoDBTableCallsigndata.Arn
    Description: DynamoDB Table for callsign data
    Export:
      Name: !Sub "${AppName}-${Env}-DynamoDBTableCallsigndata"
  LambdaFunctionCallsigndataupdaterArn:
    Value: !GetAtt LambdaFunctionCallsigndataupdater.Arn
    Description: Callsign data updater lambda function
    Export:
      Name: !Sub "${AppName}-${Env}-LambdaFunctionCallsigndataupdater"

      